spring:
   application:
      name: discovery
server:
   port: 7777
   servletPath: /michael

eureka:
   instance:
      hostname: ${vcap.application.uris[0]}
      instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${server.port}}}
      statusPageUrlPath: ${server.servletPath}/info
      healthCheckUrlPath: ${server.servletPath}/health
   client:
      serviceUrl:
         defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
      register-with-eureka: false
      fetch-registry: false
      region: default
      healthcheck:
         enabled: true
