server:
   port: 6000

eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:7777/eureka/

spring:
   application:
      name: "gateway"

zuul:
   routes:
      book:
         url: http://localhost:8084

ribbon:
   eureka:
      enabled: false