eureka.client.serviceUrl.defaultZone: http://localhost:7777/eureka/

spring:
  application:
    name: hello-service
server:
  port: 8081

spring.main.allow-bean-definition-overriding: true
 
eureka.client:
   region: default
   registryFetchIntervalSeconds: 5
