server:
   port: 8181

eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:7777/eureka/

mybatis:
   type-aliases-package: michael.slf4j.demo.mapper
spring:
   application:
      name: "web-security"
   datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: "jdbc:mysql://localhost:3306/michael?useUnicode=true;characterEncoding=utf-8"
      username: root
      password: hexin1250
   main:
      allow-bean-definition-overriding: true